project:
  type: website
  output-dir: docs

website:
  title: "Informal Caregiver Attitudes and Wellbeing"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left
    code-fold: true
    code-link: true
    code-tools: true


editor: visual